export const products = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 999,
    rating: 4.5,
    stock: 10,
    brand: "Brand A",
  },
  {
    id: 2,
    name: "Smartphone",
    category: "Electronics",
    price: 799,
    rating: 4.7,
    stock: 25,
    brand: "Brand B",
  },
  {
    id: 3,
    name: "Coffee Maker",
    category: "Home Appliances",
    price: 49,
    rating: 4.0,
    stock: 15,
    brand: "Brand C",
  },
  {
    id: 4,
    name: "Blender",
    category: "Home Appliances",
    price: 89,
    rating: 4.2,
    stock: 8,
    brand: "Brand D",
  },
  {
    id: 5,
    name: "Running Shoes",
    category: "Footwear",
    price: 120,
    rating: 4.8,
    stock: 20,
    brand: "Brand E",
  },
  {
    id: 6,
    name: "Jacket",
    category: "Clothing",
    price: 150,
    rating: 4.3,
    stock: 12,
    brand: "Brand F",
  },
  {
    id: 7,
    name: "Watch",
    category: "Accessories",
    price: 199,
    rating: 4.6,
    stock: 5,
    brand: "Brand G",
  },
  {
    id: 8,
    name: "Backpack",
    category: "Accessories",
    price: 69,
    rating: 4.4,
    stock: 18,
    brand: "Brand H",
  },
  {
    id: 9,
    name: "Headphones",
    category: "Electronics",
    price: 149,
    rating: 4.9,
    stock: 30,
    brand: "Brand I",
  },
  {
    id: 10,
    name: "T-shirt",
    category: "Clothing",
    price: 29,
    rating: 4.1,
    stock: 40,
    brand: "Brand J",
  },
];
